version: "3.9"

services:
  ansible_host:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./server:/ansible
    command: ansible-playbook host_ansi.yml

  container_fabric:
    build: 
      context: ./
      dockerfile: app/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
      - ./server:/app/server
    command: ansible-playbook fabr_ansi.yml
    depends_on:
      - ansible_host
